version: '2'

services:
  app:
    image: 'rentbike-app:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: rent-bike-app
    depends_on:
      - db
    environment:
      - JAVA_OPTS=
         -Dspring.profiles.active=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rentbike
      - SPRING_DATASOURCE_USERNAME=rentbike
      - SPRING_DATASOURCE_PASSWORD=rentbike


  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=rentbike
      - POSTGRES_PASSWORD=rentbike